# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          # install deps
          - apt-get update && apt-get install -y ninja-build meson wine mingw-w64 git wine-binfmt
          # meson setup
          - mkdir builddir
          - meson builddir
          - meson configure -Dsource=cpython builddir
          # prepare cpython code
          - git clone https://github.com/python/cpython.git cpython
          # run build
          - ninja -C builddir
